name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      # Ensure @changesets/cli is available in PATH
      - name: Setup Changesets CLI
        run: |
          echo "$(yarn bin @changesets/cli)" >> $GITHUB_PATH

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .

      - name: Create .npmrc for scoped packages
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "@convolver-player:registry=https://registry.npmjs.org/" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify NPM Auth
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called `release` in your root package.json
          publish: yarn build # We will handle actual publishing manually
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        if: steps.changesets.outputs.publishedPackages != ''
        run: |
          for PKG in ${{ steps.changesets.outputs.publishedPackages }}; do
            echo "Publishing package $PKG"
            npm publish --access public --tag latest --registry https://registry.npmjs.org/ "$PKG"
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}